site_name: AnySolve
site_url: https://docs.anysolve.ai/
theme:
  name: material
nav:
  - Home: "index.md"
  - "User Guide":
      - "Overview": "guide/overview.md"
  - "Showcase":
      - "Task: Write a Paper": "showcase/write-a-paper.md"
  - "REST API": "rest/rest.md"
  - Pricing: "pricing.md"
repo_url: https://github.com/BlackriverOrg/anysolve-docs/
