site_name: AnySolve
site_url: https://docs.anysolve.ai/
theme:
  name: material
markdown_extensions:
  - attr_list
plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: False
      css_style:
        width: "100%"
nav:
  - Home: "index.md"
  - "FAQ": "faq.md"
  - "User Guide":
      - "Overview": "guide/overview.md"
  - "Showcase":
      - "Overview": "showcase/overview.md"
      - "Task: Query Document Collection": "showcase/query-document-collection/query-knowledge-base.md"
      - "Task: Chart Generator": "showcase/chart-generator/chart-generator.md"
      - "Task: Create a HTML document": "showcase/create-html-document/create-html-document.md"
      - "Task design - Run AIs anonymized": "showcase/anonymize-ai/anonymize-ai.md"
      - "Task: Write and further improve a newspaper article": "showcase/create-newspaper-article/create-newspaper-article.md"
      - "Task: Write a Paper": "showcase/write-a-paper/write-a-paper.md"
      - "Create your own AI tool": "showcase/create-your-own-ai-tools/create-your-own-ai-tools.md"
  - "REST API": "rest/ai-api.md"
  - Community: "community.md"
  - Pricing: "pricing.md"
  - Status: "status.md"
repo_url: https://github.com/BlackriverOrg/anysolve-docs/
